name: Build package

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the package
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "!" >> README.md
          git add README.md
          git commit -m "Build package $(date)"
          git push --force origin main:dist

      - name: Release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
